dofile(DATA_DIRECTORY.. '/lib/quests/bigfoot_burden.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/demon_oak.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/grimvale.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/killing_in_the_name_of.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/svargrond_arena.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/the_cursed_crystal.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/the_queen_of_the_banshees.lua')
dofile(DATA_DIRECTORY.. '/lib/quests/their_masters_voice.lua')
