-- Atomic session-lease acquire (see docs/multichannel/ARCHITECTURE.md §5 and
-- docs/multichannel/THREAT_MODEL.md T1). Runs as a single Redis EVAL, so two
-- processes racing to acquire the same key can never both win: Redis
-- serializes script execution.
--
-- KEYS[1] = lock key, e.g. "cluster:session:<accountId>"
-- ARGV[1] = new session id (random, generated by the caller)
-- ARGV[2] = channel id of the acquiring process
-- ARGV[3] = instance id of the acquiring process
-- ARGV[4] = lease ttl in ms
-- ARGV[5] = current time in ms (caller-supplied so tests are deterministic)
--
-- Returns { acquired(0|1), sessionId, fencingToken }
-- On rejection, sessionId/fencingToken describe the current holder.

local key = KEYS[1]
local newSessionId = ARGV[1]
local channelId = ARGV[2]
local instanceId = ARGV[3]
local ttlMs = tonumber(ARGV[4])
local nowMs = tonumber(ARGV[5])

local existingExpiresAt = tonumber(redis.call('HGET', key, 'expires_at'))
if existingExpiresAt and existingExpiresAt > nowMs then
	-- Lease is held and has not expired: reject. The caller must not
	-- overwrite a live session, regardless of which process is asking.
	local currentSessionId = redis.call('HGET', key, 'session_id')
	local currentFencingToken = redis.call('HGET', key, 'fencing_token')
	return { 0, currentSessionId, currentFencingToken }
end

-- HINCRBY on a field that has never existed starts from 0 and returns 1, and
-- is never reset by release (see release.lua) - this is what makes the
-- fencing token strictly monotonic for the lifetime of this key.
local fencingToken = redis.call('HINCRBY', key, 'fencing_token', 1)
redis.call('HSET', key,
	'session_id', newSessionId,
	'channel_id', channelId,
	'instance_id', instanceId,
	'expires_at', tostring(nowMs + ttlMs))
-- Belt-and-suspenders TTL on the whole key so an abandoned lock key doesn't
-- live forever if every caller misbehaves; comfortably longer than the lease
-- itself so a legitimate renew is never at risk of the key vanishing under it.
redis.call('PEXPIRE', key, ttlMs * 4)

return { 1, newSessionId, fencingToken }
