#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path

SUPPORTED_COMPONENTS = {"quest", "npc", "monster"}
SAFE_ID = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


def build_draft(normalized: dict, target_datapack: str = "data-otservbr-global") -> tuple[dict, dict]:
    source_document = str(normalized.get("sourceDocument") or "research")
    safe_document = source_document if SAFE_ID.fullmatch(source_document) else "research"
    components: list[dict] = []
    conflicts: list[dict] = []
    skipped: list[dict] = []

    for entity in normalized.get("entities", []):
        entity_id = entity.get("id")
        entity_type = entity.get("type")
        status = entity.get("canary", {}).get("status")
        if status == "matched":
            conflicts.append({
                "id": entity_id,
                "type": entity_type,
                "name": entity.get("name"),
                "reason": "entity already exists in Canary",
                "matches": entity.get("canary", {}).get("matches", []),
            })
            continue
        if entity_type not in SUPPORTED_COMPONENTS:
            skipped.append({
                "id": entity_id,
                "type": entity_type,
                "name": entity.get("name"),
                "reason": "entity type is not generated by the content preview renderer",
            })
            continue
        components.append({
            "id": entity_id,
            "type": entity_type,
            "name": entity.get("name"),
            "dependsOn": [],
            "sourceRefs": ["research-document", "canary-conventions"],
        })

    quest_ids = [item["id"] for item in components if item["type"] == "quest"]
    support_ids = [item["id"] for item in components if item["type"] in {"npc", "monster"}]
    for component in components:
        if component["id"] in quest_ids:
            component["dependsOn"] = support_ids

    task_id = f"{safe_document}_draft"
    task = {
        "schemaVersion": "1.0",
        "taskId": task_id,
        "type": "content_bundle",
        "name": f"{safe_document.replace('_', ' ').title()} Draft Content Pack",
        "description": "Dry-run task draft generated from normalized research. Existing Canary entities are excluded.",
        "targetDatapack": target_datapack,
        "dryRun": True,
        "requestedBy": "ai-agent",
        "tags": ["research-derived", "draft", "dry-run"],
        "sources": [
            {
                "id": "research-document",
                "kind": "manual",
                "title": f"Normalized research document: {source_document}",
                "checkedAt": date.today().isoformat(),
                "confidence": "medium",
                "notes": "Facts and original source references remain in the normalized research artifact and require human review.",
            },
            {
                "id": "canary-conventions",
                "kind": "repository",
                "title": "Canary Lua content conventions",
                "url": "https://github.com/blakinio/canary",
                "checkedAt": date.today().isoformat(),
                "confidence": "high",
                "notes": "Source of truth for implementation shape and repository paths.",
            },
        ],
        "contentBundle": {
            "components": components,
            "requestedIds": ([
                {
                    "namespace": "storage",
                    "count": max(1, len(quest_ids) * 3),
                    "min": 390000,
                    "max": 399999,
                    "purpose": "research-derived quest progress and reward state",
                },
                {
                    "namespace": "actionId",
                    "count": max(1, len(quest_ids) * 2),
                    "min": 59000,
                    "max": 59999,
                    "purpose": "research-derived interactive quest objects",
                },
            ] if quest_ids else []),
            "mapRequirements": ([
                "Map work remains manual and must be reviewed in a map editor.",
                "Do not modify OTBM or items.otb through this pipeline.",
            ] if quest_ids else []),
            "manualSteps": [
                "Review all normalized facts against their cited sources.",
                "Resolve every conflict before considering active datapack integration.",
                "Validate generated previews and references after manual integration.",
            ],
        },
    }

    report = {
        "schemaVersion": "1.0",
        "sourceDocument": source_document,
        "taskId": task_id,
        "summary": {
            "generatedComponents": len(components),
            "blockedConflicts": len(conflicts),
            "skippedUnsupported": len(skipped),
            "readyForPipeline": bool(components) and not conflicts,
        },
        "conflicts": conflicts,
        "skipped": skipped,
    }
    return task, report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--normalized", required=True, type=Path)
    parser.add_argument("--task-output", required=True, type=Path)
    parser.add_argument("--report-output", required=True, type=Path)
    parser.add_argument("--target-datapack", default="data-otservbr-global")
    args = parser.parse_args()

    task, report = build_draft(
        json.loads(args.normalized.read_text(encoding="utf-8")),
        args.target_datapack,
    )
    args.task_output.parent.mkdir(parents=True, exist_ok=True)
    args.report_output.parent.mkdir(parents=True, exist_ok=True)
    args.task_output.write_text(json.dumps(task, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    args.report_output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(report["summary"], indent=2))
    return 2 if report["conflicts"] else (0 if report["summary"]["generatedComponents"] else 1)


if __name__ == "__main__":
    raise SystemExit(main())
