local quest = {
	name = "The Postman Missions",
	startStorageId = Storage.Quest.U7_24.ThePostmanMissions.Mission01,
	startStorageValue = 1,
	missions = {
		[1] = {
			name = "Mission 01 - Check Postal Routes",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission01,
			missionId = 10252,
			startValue = 1,
			endValue = 6,
			states = {
				[1] = "Kevin wants you to travel with Captain Bluebear to Carlin.",
				[2] = "Kevin wants you to travel with Uzon in Femor Hills to Edron.",
				[3] = "Kevin wants you to travel with Captain Seahorse to Venore.",
				[4] = "Kevin wants you to travel with Brodrosch to Cormaya",
				[5] = "You have checked the Postal Routes, report back to Kevin!",
				[6] = "You have reported back that you have completed the mission.",
			},
		},
		[2] = {
			name = "Mission 02 - Fix Mailbox",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission02,
			missionId = 10253,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "Kevin wants you to fix one of their Mailboxes located on Folda with a crowbar.",
				[2] = "You have fixed the mailbox, report back to Kevin!",
				[3] = "You have reported back that you have completed the mission.",
			},
		},
		[3] = {
			name = "Mission 03 - Bill Delivery",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission03,
			missionId = 10254,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "Kevin wants you to deliver a bill to the stage magician David Brassacres. \z
				He's hiding from his creditors somewhere in Venore.",
				[2] = "You have delivered the bill to the stage magician David Brassacres, report back to Kevin!",
				[3] = "You have reported back that you have completed the mission.",
			},
		},
		[4] = {
			name = "Mission 04 - Aggressive Dogs",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission04,
			missionId = 10255,
			startValue = 1,
			endValue = 2,
			states = {
				[1] = "Kevin has asked you to deliver 20 Bones to him.",
				[2] = "You have delivered 20 Bones to Kevin.",
			},
		},
		[5] = {
			name = "Mission 05 - Present Delivery",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission05,
			missionId = 10256,
			startValue = 1,
			endValue = 4,
			states = {
				[1] = "Kevin has asked you to retrieve the present behind the door on the \z
				lower right side of his room and deliver it to Dermot in Fibula.",
				[2] = "Deliver the present to Dermot in Fibula.",
				[3] = "You have delivered the present to Dermot, report back to Kevin!",
				[4] = "You have reported back that you have completed the mission.",
			},
		},
		[6] = {
			name = "Mission 06 - New Uniforms",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission06,
			missionId = 10257,
			startValue = 1,
			endValue = 13,
			states = {
				[1] = "Kevin has asked you to travel to Venore and negotiate with Hugo for new uniforms.",
				[2] = "Hugo said that his dog ate the last dress pattern they used and he \z
				has no clue where Kevin Postner got it from, go ask Kevin.",
				[3] = "Kevin wants you to ask the great Technomancer Talphion in Kazordoon for the technical details.",
				[4] = "Talphion will send a copy to Kevin, report back to Kevin.",
				[5] = "Kevin wants you to ask Queen Eloise of Carlin for the perfect colours.",
				[6] = "Queen Eloise said she will send some color samples via mail to Kevin, report back to Kevin.",
				[7] = "Kevin has asked you to go to Noodles and find out what he dislikes the most: \z
				mouldy cheese, a piece of fur or a banana skin.",
				[8] = "Noodles seems to like banana skin, check if he likes dirty fur.",
				[9] = "Noodles seems to like dirty fur, check if he likes mouldy cheese.",
				[10] = "Noodles dislikes mouldy cheese! Report back to Kevin.",
				[11] = "Kevin wants you to tell Hugo that they order those uniforms.",
				[12] = "Hugo has agreed to make the uniforms, report back to Kevin!",
				[13] = "You have reported back that you have completed the mission.",
			},
		},
		[7] = {
			name = "Mission 07 - Measurements",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission07,
			missionId = 10258,
			startValue = 1,
			endValue = 9,
			states = {
				[1] = "Kevin wants you to bring him the measurements of Benjamin, Lokur, Dove, Liane, Chrystal and Olrik.",
				[2] = "You have received the measurements from 1 of 6 post officers.",
				[3] = "You have received the measurements from 2 of 6 post officers.",
				[4] = "You have received the measurements from 3 of 6 post officers.",
				[5] = "You have received the measurements from 4 of 6 post officers.",
				[6] = "You have received the measurements from 5 of 6 post officers.",
				[8] = "You have received all measurements, report back to Kevin!",
				[9] = "You have reported back that you have completed the mission.",
			},
		},
		[8] = {
			name = "Mission 08 - Missing Courier",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission08,
			missionId = 10259,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "Kevin wants you to find the missing courier Waldo or at least his posthorn.",
				[2] = "You have found Waldos posthorn.",
				[3] = "You have reported back that you have completed the mission.",
			},
		},
		[9] = {
			name = "Mission 09 - Dear Santa",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission09,
			missionId = 10260,
			startValue = 1,
			endValue = 4,
			states = {
				[1] = "Kevin wants you to deliver som letters to Santa Claus on Vega.",
				[2] = "You have retrieved the letters, deliver them to Santa Claus on Vega.",
				[3] = "You have delivered the letters to Santa Claus on Vega.",
				[4] = "You have reported back that you have completed the mission.",
			},
		},
		[10] = {
			name = "Mission 10 - Mintwallin",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Mission10,
			missionId = 10261,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "Kevin wants you to deliver a letter  to Markwin, king of Mintwallin from his mother.",
				[2] = "You have delivered the letter to Markwin.",
				[3] = "You have reported back that you have completed the mission.",
			},
		},
		[11] = {
			name = "Postman Rank",
			storageId = Storage.Quest.U7_24.ThePostmanMissions.Rank,
			missionId = 10262,
			startValue = 1,
			endValue = 5,
			states = {
				[1] = "Assistant Postman",
				[2] = "Postman",
				[3] = "Grand Postman",
				[4] = "Grand Postman for Special Operations",
				[5] = "Arch Postman",
			},
		},
	},
}

return quest
