local quest = {
	name = "The Rookie Guard",
	startStorageId = Storage.Quest.U9_1.TheRookieGuard.Questline,
	startStorageValue = 1,
	missions = {
		[1] = {
			name = "Mission 01: A Taste of Things to Come",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission01,
			missionId = 10397,
			startValue = 1,
			endValue = 1,
			states = {
				[1] = "",
			},
		},
		[2] = {
			name = "Mission 02: Defence!",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission02,
			missionId = 10398,
			startValue = 1,
			endValue = 5,
			states = {
				[1] = "Vascalir promised you some equipment, but first you need to build up some muscles. Find a big pile of stone in a barn to the north and use it to get a heavy stone.",
				[2] = "You retrieved one stone from the big pile. Climb onto the roof of either Norma's bar, Obi's shop or the academy to find a catapult to use it on.",
				[3] = "You loaded a stone on one of the catapults. One more to go! Climb onto the roof of either Norma's bar, Obi's shop or the academy to find a catapult to load with a heavy stone.",
				[4] = "Two of the four catapults on the roofs are loaded. That should be enough to build up a decent defence. Return to Vascalir to turn in your quest.",
				[5] = "You made sure that Rookgaard's defences are at their best. If the orcs try to enter the village, they won't have an easy time!",
			},
		},
		[3] = {
			name = "Mission 03: A Rational Request",
			storageId = Storage.Quest.U9_1.TheRookieGuard.RatKills,
			missionId = 10399,
			startValue = 0,
			endValue = 5,
			description = function(player)
				return string.format(
					"Vascalir sent you to the Rookgaard sewers to kill 5 rats. You have already killed %d/5. \z
				Return to Vascalir once you're done.",
					(math.max(player:getStorageValue(Storage.Quest.U9_1.TheRookieGuard.RatKills), 0))
				)
			end,
		},
		[4] = {
			name = "Mission 04: Home-Brewed",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission04,
			missionId = 10400,
			startValue = 1,
			endValue = 6,
			states = {
				[1] = "Vascalir doesn't have a job for you at the moment. He sent you to Lily in the south-west of town for another mission.",
				[2] = "Lily gave you a bag with fresh herbs that need to be delivered to Hyacinth outside of the village. Leave the village to the north and walk east to find his little hut up a mountain.",
				[3] = "You've delivered the fresh herbs to Hyacinth. He still has a reward for you though - make sure to talk to him again!",
				[4] = "Hyacinth has another reward for you - make sure to talk to him again with enough space in your inventory.",
				[5] = "You've delivered the herbs to Hyacinth and got potions and a ring as reward. Save the potions for when you're low on health and wear the ring if you want to regain health faster. Return to Vascalir.",
				[6] = "You've told Vascalir about your successful delivery. The next mission awaits.",
			},
		},
		[5] = {
			name = "Mission 05: Web of Terror",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission05,
			missionId = 10401,
			startValue = 1,
			endValue = 6,
			states = {
				[1] = "Vascalir sent you to the spider queen's lair to retrieve a web sample. Leave the village to the north and cross the bridge to the north-west to find the lair. Look for greasy blue stones.",
				[2] = "You've covered yourself in grease. It's a bit disgusting, but the spider queen will not be able to smell you for about two minutes. Enter her cave and USE an intact spider web to retrieve a sample.",
				[3] = "You retrieved some of the spider queen's web. Return to Vascalir and try not to get caught by the queen on the way out!",
				[4] = "The spider queen caught you in her net. If you had a sample of her web, you've lost it. Find a way out of her net and retry!",
				[5] = "Vascalir took the sample from you. He still has a studded armor for you - talk to him once you have enough space in your inventory.",
				[6] = "You've brought the spider queen's web back to Vascalir. This will definitely come in handy later on.",
			},
		},
		[6] = {
			name = "Mission 06: Run Like a Wolf",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission06,
			missionId = 10402,
			startValue = 1,
			endValue = 7,
			states = {
				[1] = "Vascalir sent you to Tom the Tanner, who can be found to the west of the academy. There you will get your next mission.",
				[2] = "Leave the village to the north and walk north-east into the forest to find the wolves' den that Tom told you about. Hopefully you will find that poacher to take some leather from him!",
				[3] = "You've entered the wolves' den - that was a one-way fall, but luckily you didn't get hurt. The poacher you were looking for is dead - but that doesn't mean you can't get some war wolf leather!",
				[4] = "You've skinned a war wolf - but you alerted the wolf pack! Run to the exit, quickly!",
				[5] = "RUN! You have only a limited time to reach the exit with the war wolf leather!",
				[6] = "Phew - you managed to get out of the wolves' den in time. Return to Tom to finish your mission.",
				[7] = "Tom gave you a pair of leather boots as reward for your good work. Vascalir surely has a new mission for you now.",
			},
		},
		[7] = {
			name = "Mission 07: Attack!",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission07,
			missionId = 10403,
			startValue = 1,
			endValue = 2,
			states = {
				[1] = "While you were gone, trolls have infiltrated the academy and set it on fire! Enter the burning vault deep underground and try to recover the copy of the book of orc language before it's destroyed.",
				[2] = "You've done all you could - but unfortunately the book is lost. No need to lose heart though - there is still hidden knowledge about the orc language in the village, and the next mission awaits.",
			},
		},
		[8] = {
			name = "Mission 08: Less Risk - More Fun",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission08,
			missionId = 10404,
			startValue = 1,
			endValue = 2,
			states = {
				[1] = "Before getting revenge on the trolls, eliminate the risk of losing money on the way. Paulie has an interesting bonus offer for you if you deposit your money at the bank. Find him below the academy.",
				[2] = "You've done as Vascalir asked and talked to Paulie. Remember to always leave your gold on your account! That way there's no risk of losing it.",
			},
		},
		[9] = {
			name = "Mission 09: Rock 'n Troll",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission09,
			missionId = 10405,
			startValue = 1,
			endValue = 10,
			states = {
				[1] = "Enter the troll lair to the north of the village and find the new tunnel which the trolls dug and used to infiltrate the Rookgaard academy. There, you need to find a way to destroy it.",
				[2] = "Open the chests in the tunnel and use the pick on the 5 beams to weaken the structure and make the tunnel collapse.",
				[3] = "You've weakened one of five beams.",
				[4] = "You've weakened two of five beams.",
				[5] = "You've weakened three of five beams.",
				[6] = "You've weakened four of five beams.",
				[7] = "You've weakened all the beams! Hurry out of the tunnel before it collapses!",
				[8] = "The tunnel collapsed behind you. Time to return to Vascalir.",
				[9] = "Vascalir rewarded you with experience, but there's still something he has to give you. You should talk to him again.",
				[10] = "The trolls will not be able to enter the academy via their tunnel again. The village is safe for now - at least from trolls.",
			},
		},
		[10] = {
			name = "Mission 10: Tomb Raiding",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission10,
			missionId = 10406,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "Leave the village to the north and walk south-east to find the haunted graveyard. Descend into the crypt and find a sarcophagus that might still contain a fleshy bone. Bring it to Vascalir.",
				[2] = "You've brought the fleshy bone back to Vascalir. Talk to him again to receive your reward.",
				[3] = "You managed to get a fleshy bone from the crypt! Who knows what Vascalir plans with it - but this is going to be good.",
			},
		},
		[11] = {
			name = "Mission 11: Sweet Poison",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission11,
			missionId = 10407,
			startValue = 1,
			endValue = 5,
			states = {
				[1] = "Leave the village to the north and cross the bridge to the west, then walk south-west to find a wasp lair. Make sure you don't lose the flask Vascalir gave you.",
				[2] = "You've found the wasp lair. Kill one wasp and use the empty flask on its dead body to retrieve some of its poison.",
				[3] = "You've retrieved some lethal wasp poison. Bring it back to Vascalir to complete the mission.",
				[4] = "You brought Vascalir the highly toxic poison. You should talk to him again to receive your reward.",
				[5] = "You've retrieved highly toxic wasp poison for Vascalir. It's time for your final challenge.",
			},
		},
		[12] = {
			name = "Mission 12: Into The Fortress",
			storageId = Storage.Quest.U9_1.TheRookieGuard.Mission12,
			missionId = 10408,
			startValue = 1,
			endValue = 15,
			states = {
				[1] = "This is it - the infiltration of the orc fortress and revenge on Kraknaknork awaits. Get the required items from a chest in the academy near the bank.",
				[2] = "You've got all items you need to finally kill Kraknaknork. Don't lose them, and carefully make your way towards the orc fortress located in the far west of Rookgaard. Leave the village to the north.",
				[3] = "You've knocked out the unsuspecting orc. USE the orc before it wakes up again to disguise yourself as an orc!",
				[4] = "Even your mom wouldn't recognise you. You might not be able to fool all orcs in your disguise, but it should be enough to walk past the orc guarding the entrance.",
				[5] = "You managed to sneak into the fortress. Use the fleshy bone and click on the elite orc guard with the crosshairs to create a distraction!",
				[6] = "The guard is indeed very distracted - he smells delicious. At least to the wild dogs that entered the scene. This is the perfect time to enter the lower levels of the orc fortress.",
				[7] = "You're inside the orc fortress! Now you need to find a kitchen and something that looks like a soup cauldron. Use the wasp poison on the cauldron to create an evil surprise for Kraknaknork.",
				[8] = "You \"spiced up\" Kraknaknork's breakfast. Let's see how strong he still is after his meal. Proceed further into the fortress - and keep your tarantula trap ready.",
				[9] = "You managed to slow down the furious orc berserker. Now, run through the teleporter while he isn't close to it!",
				[10] = "You've entered Kraknaknork's room. Find a way to get rid of the energy barriers.",
				[11] = "You solved the riddle of the energy barriers. The way to the throne room should be clear - for a short time. Be prepared for a massive fight!",
				[12] = "You've entered Kraknaknork's throne room. Fight him! You can back out at any time via the teleporter, but you'll have to start the battle over. Once he is dead, enter the teleporter near his throne.",
				[13] = "You've vanquished Kraknaknork and found his treasure room. You can probably take a few things from there before you leave - he wouldn't care anymore.",
				[14] = "With the last bit of Kraknaknork's energy, you were teleported out of the fortress. Time to return to Vascalir victoriously.",
				[15] = "You've vanquished Kraknaknork and brought peace to the village of Rookgaard. It will soon be time for you to leave for the Isle of Destiny, choose a vocation and enter the open world of Tibia.",
			},
		},
	},
}

return quest
