local quest = {
	name = "The Secret Library",
	startStorageId = Storage.Quest.U11_80.TheSecretLibrary.Questlog,
	startStorageValue = 1,
	missions = {
		[1] = {
			name = "High and Dry",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.SmallIslands.Questline,
			missionId = 10461,
			startValue = 1,
			endValue = 4,
			states = {
				[1] = "Dedoras asked for you to talk to Charles, he knows about a small island.",
				[2] = "You got stucked on this island. You must discover how to leave.",
				[3] = "You successfully built a raft and used the starts to navigate your way through the waves. At least you found something of interest on the deserted island.",
				[4] = "Congratulations you completed this mission.",
			},
		},
		[2] = {
			name = "Liquid Death",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.LiquidDeath.Questline,
			missionId = 10462,
			startValue = 1,
			endValue = 8,
			states = {
				[1] = "Dedoras has sent you to Spectulus in the Edron Academy. Rumors of strange fishmen in the Tiquanda region may be connected to some of the research the scholar conducted.",
				[2] = "Spectulus asked you to check out the rumors of strange fishmen in the jungles of northern Tiquanda. A small sunken temple is said to be overrun by strange fish-like creatures.",
				[3] = "You found a sunken temple deep in the Tiquanda jungle. Spectulus will help you enter the vortex at the entrance. Find out what happened there and take care of the fish-like aggressors...",
				[4] = "Part IV",
				[5] = "Part V",
				[6] = "Part VI",
				[7] = "Brokul has been defeated and now you can talk with Spectulus or Dedoras what you found about the fishmen.",
				[8] = "Congratulations you completed this mission.",
			},
		},
		[3] = {
			name = "Asuri - The Lament",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.Asuras.Questline,
			missionId = 10463,
			startValue = 1,
			endValue = 7,
			states = {
				[1] = "Go to Asuri Palace in Port Hope.",
				[2] = "You were able to assemble an instrument with the objects found. That should work for something.",
				[3] = "You must talk with the dead girl's mother, Gail, at Port Hope.",
				[4] = "With a heavy heart you used a piece of ebony as well as the skull and hair of an unfortunate maiden to create a bone fiddle. By playing the Peacock Ballad you should be able to open the viollet portal.",
				[5] = "You may enter the viollet portal. Check if there is something useful there.",
				[6] = "In a secret room of the Asura Palace you discovered an old writing desk that contains an ancient map. This must be a hint to the secret library you are searching for.",
				[7] = "Congratulations you completed this mission.",
			},
		},
		[4] = {
			name = "The Order of the Falcon",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.FalconBastion.Questline,
			missionId = 10464,
			startValue = 1,
			endValue = 3,
			states = {
				[1] = "It is said that an ancient order of knights once resided in Edron. The knights disappeared a long time ago but their abandoned outpost is still there. The place may yet hold some surprises.",
				[2] = "You defeated Grand Master Oberon in mortal combat. The Falcon Order may have lost its glory a long time ago but you are just getting started.",
				[3] = "Congratulations you completed this mission.",
			},
		},
		[5] = {
			name = "The Path of Defiances",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.Darashia.Questline,
			missionId = 10465,
			startValue = 1,
			endValue = 9,
			states = {
				[1] = "Go to Darashia and find out about the mysterious statue.",
				[2] = "After you have been swallowed by a sand vortex you have entered a hidden desert area. A voice of unknown origin has informed you that you will have to face some challenges.",
				[3] = "Part III",
				[4] = "Part IV",
				[5] = "Part V",
				[6] = "Part VI",
				[7] = "Part VII",
				[8] = "You have found a book page in a chest. It seems to contain very useful information, but you are not capable to read it. At this point you have to speak with an expert.",
				[9] = "Congratulations you completed this mission.",
			},
		},
		[6] = {
			name = "Bursting at the Seams",
			storageId = Storage.Quest.U11_80.TheSecretLibrary.MoTA.Questline,
			missionId = 10466,
			startValue = 1,
			endValue = 8,
			states = {
				[1] = "Dedoras told you where to search for leads to the Veiled Hoard: the museum in Thais, a fishmen temple in Tiquanda, an order fortress in Edron, the Asuri Palace and a deserted isle.",
				[2] = "You talked with Gareth and now you may pass trougth the door.",
				[3] = "Part III",
				[4] = "Part IV",
				[5] = "Part V",
				[6] = "You successfully entered the Veiled Hoard of Zathroth. However, countless secret and vast knowledge still lie ahead.",
				[7] = "You have reported Gareth about the enigmatic inscription you have found in the chamber of doom. He was able to decipher it for you and referred to Dedoras in Cormaya for further assistance.",
				[8] = "Congratulations you completed this mission.",
			},
		},
	},
}

return quest
