
local quest = {
	name = "20 Years a Cook",
	startStorageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
	startStorageValue = 1,
	missions = {
		[1] = {
		name = "The lair of the Draccoon",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10503,
		startValue = 1,
		endValue = 2,
		description = "Find the Draccoon in his lair. The secret entrance is supposed to be found somewhere in the Venorean dumpster area.",
		},
		[2] = {
		name = "An old friend",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10504,
		startValue = 2,
		endValue = 3,
		description = "Look for an old friend of the Draccoon. The Draccoon assumes his friend still lives in an appartment in the upper levels of Kazordoon.",
		},
		[3] = {
		name = "Sad news",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10505,
		startValue = 3,
		endValue = 4,
		description = "Ratha, the Draccoon's old friend has met his ultimely demise. Travel to the Draccoon's lair to inform about Ratha's fate",
		},
		[4] = {
		name = "Ghost hunt",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10506,
		startValue = 4,
		endValue = 5,
		description = "Meet the ally of the Draccoon in Ratha's quarters in Kazordoon and extract Ratha's spirit.",
	},
	[5] = {
		name = "Ghost hunt",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10507,
		startValue = 5,
		endValue = 6,
		description = "Travel to the Draccoon's lair to learn how to proceed.",
	},
	[6] = {
		name = "The potion",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10508,
		startValue = 6,
		endValue = 7,
		description = "Drink a 'potion of spirit of talking' in the Draccoon's lair.",
	},
	[7] = {
		name = "The potion",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10509,
		startValue = 7,
		endValue = 8,
		description = "You accidentally drunk Ratha. Better talk to the Draccoon about it.",
	},
	[8] = {
		name = "Revenge best served fried!",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10510,
		startValue = 8,
		endValue = 9,
		description = "Travel to the house of the Fryclops and find a way to remove him from the picture. The Draccoon's allies will provide a secret access from somewhere in the south of the Ghostlands.",
	},
	[9] = {
		name = "An eye for an eye",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10511,
		startValue = 9,
		endValue = 10,
		description = "You triumphed over the Fryclops.\nTalk to the Draccoon about your success.",
	},
	[10] = {
		name = "In charge",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10512,
		startValue = 10,
		endValue = 11,
		description = "Travel to Edron to find the Draccoon's ally. Steal charged crystals from some demons to power up the Fryclop's machine.",
		},
	},
}

return quest


--[[name = "20 Years a Cook",
startStorageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
startStorageValue = 1,
missions = {
	[1] = {
		name = "The lair of the Draccoon",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10451,
		startValue = 1,
		endValue = 2,
		description = "Find the Draccoon in his lair. The secret entrance is supposed to be found somewhere in the Venorean dumpster area.",
	},
	[2] = {
		name = "An old friend",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10452,
		startValue = 2,
		endValue = 3,
		description = "Look for an old friend of the Draccoon. The Draccoon assumes his friend still lives in an appartment in the upper levels of Kazordoon.",
	},
	[3] = {
		name = "Sad news",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10453,
		startValue = 3,
		endValue = 4,
		description = "Ratha, the Draccoon's old friend has met his ultimely demise. Travel to the Draccoon's lair to inform about Ratha's fate",
	},
	[4] = {
		name = "Ghost hunt",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10454,
		startValue = 4,
		endValue = 5,
		description = "Meet the ally of the Draccoon in Ratha's quarters in Kazordoon and extract Ratha's spirit.",
	},
	[5] = {
		name = "Ghost hunt",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10455,
		startValue = 5,
		endValue = 6,
		description = "Travel to the Draccoon's lair to learn how to proceed.",
	},
	[6] = {
		name = "The potion",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10456,
		startValue = 6,
		endValue = 7,
		description = "Drink a 'potion of spirit of talking' in the Draccoon's lair.",
	},
	[7] = {
		name = "The potion",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10457,
		startValue = 7,
		endValue = 8,
		description = "You accidentally drunk Ratha. Better talk to the Draccoon about it.",
	},
	[8] = {
		name = "Revenge best served fried!",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10458,
		startValue = 8,
		endValue = 9,
		description = "Travel to the house of the Fryclops and find a way to remove him from the picture. The Draccoon's allies will provide a secret access from somewhere in the south of the Ghostlands.",
	},
	[9] = {
		name = "An eye for an eye",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10459,
		startValue = 9,
		endValue = 10,
		description = "You triumphed over the Fryclops.\nTalk to the Draccoon about your success.",
	},
	[10] = {
		name = "In charge",
		storageId = Storage.Quest.U13_30.TwentyYearsACook.QuestLine,
		missionId = 10460,
		startValue = 10,
		endValue = 11,
		description = "Travel to Edron to find the Draccoon's ally. Steal charged crystals from some demons to power up the Fryclop's machine.",
	},
},]]--
