local questModules = {
	"001_the_queen_of_the_banshees",
	"002_the_paradox_tower",
	"003_spike_task",
	"004_a_father_s_burden",
	"005_bigfoot_s_burden",
	"006_children_of_the_revolution",
	"007_factions",
	"008_friends_and_traders",
	"009_hot_cuisine",
	"010_in_service_of_yalahar",
	"011_killing_in_the_name_of",
	"012_outfit_and_addon_quests",
	"013_sam_s_old_backpack",
	"014_sea_of_light",
	"015_secret_service",
	"016_the_ancient_tombs",
	"017_the_ape_city",
	"018_the_beginning",
	"019_the_djinn_war_efreet_faction",
	"020_the_djinn_war_marid_faction",
	"021_the_hidden_city_of_beregar",
	"022_the_ice_islands_quest",
	"023_the_inquisition",
	"024_the_postman_missions",
	"025_the_shattered_isles",
	"026_the_thieves_guild",
	"027_the_travelling_trader_quest",
	"028_the_explorer_society",
	"029_the_ultimate_challenges",
	"030_the_white_raven_monastery",
	"031_tibia_tales",
	"032_unnatural_selection",
	"033_what_a_foolish_quest",
	"034_wrath_of_the_emperor",
	"035_oramond",
	"036_forgotten_knowledge",
	"037_the_first_dragon",
	"038_cults_of_tibia",
	"039_dangerous_depths",
	"040_adventurers_guild",
	"041_dawnport",
	"042_the_rookie_guard",
	"043_the_new_frontier",
	"044_spirithunters_quest",
	"045_threatened_dreams",
	"046_blood_brothers",
	"047_grave_danger",
	"048_the_outlaw_camp",
	"049_the_secret_library",
	"050_the_dream_courts",
}

local catalog = dofile(CORE_DIRECTORY .. "/lib/core/quests/catalog.lua")

return catalog.build(DATA_DIRECTORY .. ".lib.core.quests.catalog", questModules)
