# syntax=docker/dockerfile:1.7

# Stage 1: Download all dependencies
FROM ubuntu:24.04 AS dependencies

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
ENV TZ=Etc/UTC
ARG VCPKG_FEED_URL
ARG VCPKG_FEED_USERNAME
ARG VCPKG_BINARY_SOURCES
ENV VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES}

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
	apt-get update && apt-get install -y --no-install-recommends cmake git \
	unzip build-essential ca-certificates curl zip unzip tar \
	pkg-config ninja-build autoconf automake libtool glibc-tools \
	python3 mono-complete tzdata \
	&& ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
	&& echo "${TZ}" > /etc/timezone \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY vcpkg.json /opt
RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ' | tr -d '\r\n') \
    && echo "vcpkg commit ID: '$vcpkgCommitId'" \
    && git clone https://github.com/microsoft/vcpkg.git \
    && cd vcpkg \
    && git fetch origin \
    && git checkout "$vcpkgCommitId" \
    && ./bootstrap-vcpkg.sh

WORKDIR /opt/vcpkg
COPY vcpkg.json /opt/vcpkg/
RUN --mount=type=secret,id=github_token \
	--mount=type=cache,target=/opt/vcpkg/downloads \
	--mount=type=cache,target=/opt/vcpkg/buildtrees \
	--mount=type=cache,target=/opt/vcpkg/packages \
	--mount=type=cache,target=/root/.cache/vcpkg \
	set -euo pipefail \
	&& NUGET_PATH=$(/opt/vcpkg/vcpkg fetch nuget | tail -n 1) \
	&& NUGET_AUTH_TOKEN=$(cat /run/secrets/github_token) \
	&& mono "$NUGET_PATH" sources add \
		-source "${VCPKG_FEED_URL}" \
		-storepasswordincleartext \
		-name "GitHubPackages" \
		-username "${VCPKG_FEED_USERNAME}" \
		-password "${NUGET_AUTH_TOKEN}" \
	&& mono "$NUGET_PATH" setapikey "${NUGET_AUTH_TOKEN}" -source "${VCPKG_FEED_URL}" \
	&& /opt/vcpkg/vcpkg --feature-flags=binarycaching,manifests,versions install

# Stage 2: create build
FROM dependencies AS build
WORKDIR /srv/build
COPY src ./src
COPY cmake ./cmake
COPY recompile.sh CMakeLists.txt CMakePresets.json vcpkg.json ./
RUN ./recompile.sh "/opt"

# Stage 3: execute
FROM ubuntu:24.04 AS prod
COPY --from=build /srv/build/build/linux-release/bin/canary /bin/canary
WORKDIR /srv/canary
ENTRYPOINT ["/srv/canary/start.sh", "canary"]

