return {
	enabled = false,
	databaseEnabled = true,
	flushIntervalSeconds = 300,
	minimumSessionSeconds = 60,
	combatTimeoutSeconds = 120,
	includeStaff = false,
	trackPvP = false,
	trackSpells = true,
	trackMonsters = true,
	trackDamageTypes = true,
	trackSupplies = false,
	trackLoot = false,
	anonymizePlayers = false,
	queueLimit = 10000,
	detailBatchSize = 250,
	maxRetryAttempts = 5,
	retryBaseDelaySeconds = 30,
	retryMaxDelaySeconds = 900,
	deadLetterQueueLimit = 1000,
	detailLevel = 1,
	levelBrackets = { 50, 100, 200, 300, 400, 600, 800, 1000 },
	excludedPlayerNames = {},
	excludedAccountTypes = { ACCOUNT_TYPE_GAMEMASTER, ACCOUNT_TYPE_GOD },
}
