---
name: Analysis - Review Dog

on:
  pull_request:
    paths:
      - "src/**"
  push:
    paths:
      - "src/**"

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"
          cancel_others: true

      - name: Check out code.
        uses: actions/checkout@main

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3

      - name: Setup cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: cppcheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE"
          cppcheck --version
          reviewdog -reporter=github-pr-check -runners=cppcheck
