---
name: Build - macOS (dummy)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "src/**"

jobs:
  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: macos-${{ matrix.buildtype }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        buildtype: [macos-release, macos-debug]

    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
